

<script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css">
<script type="text/javascript">
$(document).ready(function() {
    $('.table').DataTable({
    	language:{
		    "sProcessing":     "Procesando...",
		    "sLengthMenu":     "Mostrar _MENU_ registros",
		    "sZeroRecords":    "No se encontraron resultados",
		    "sEmptyTable":     "Ningún dato disponible en esta tabla",
		    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
		    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
		    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
		    "sInfoPostFix":    "",
		    "sSearch":         "Buscar:",
		    "sUrl":            "",
		    "sInfoThousands":  ",",
		    "sLoadingRecords": "Cargando...",
		    "oPaginate": {
		        "sFirst":    "Primero",
		        "sLast":     "Último",
		        "sNext":     "Siguiente",
		        "sPrevious": "Anterior"
		    },
		    "oAria": {
		        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
		        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
		    }
		}
    });
} );
</script>
<div class="container">
		<div class="header" style="margin-bottom: 20px">
			<div class="col-md-9">
				<h3>EINSCHREIBEFORMULAR SAT 2017- 2018</h3>
				<h4><i>Formulario de inscripción SAT 2017- 2018</i></h4>
			</div>
			<div class=" text-center">
				<?php echo Html::img("logo.jpg","logo",'style="margin-top: 20px;width:150px"') ?>
			</div>
		</div>
		<?php View::content() ?>
		<div class="text-center">
			<h3>Lista de Registros</h3>
			<?php echo Html::link("panel/","Ir al Panel") ?>
		</div>
		<table class="table table-bordered">
			<thead>
				<th>Colegio</th>
				<th>Nombre</th>
				<th>Curso</th>
				<th>Fecha Nacimiento</th>
				<th>Email</th>
				<th>Celular</th>
				<th></th>
			</thead>
			<?php foreach ($registros as $key => $value): ?>
				<tr>
					<td><?php echo $value->colegio ?></td>
					<td><?php echo $value->nombre ?></td>
					<td><?php echo $value->curso ?></td>
					<td><?php echo $value->fechaDeNacimiento ?></td>
					<td><?php echo $value->mail ?></td>
					<td><?php echo $value->celular ?></td>
					<td>
						<div class="btn-group">
							<?php echo Html::link("registro/ver/$value->id","Ver","class='btn btn-default btn-xs'") ?>
							<?php echo Html::link("registro/borrar/$value->id","Borrar","class='btn btn-danger btn-xs' onclick='if(!confirm(\"Estas Seguro?\")){ return false;}'") ?>
							<?php echo Html::link("pdf/index/{$value->id}","Ver Pdf","class='btn btn-default btn-xs' target='_blank'") ?>
							<?php echo Html::link("index/antes_de_enviar/{$value->id}","Enviar Correo","class='btn btn-default btn-xs' ") ?>
							<?php echo Html::link("index/send_mail/{$value->id}","Enviar a Correo de Registro","class='btn btn-default btn-xs' ") ?>
						</div>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
</div>