<div class="container">
    
    <div class="text-center">
        <h2>EINSCHREIBEFORMULAR SAT 2017- 2018</h2>
        <h3>Formulario de inscripción SAT 2017- 2018</h3>
        <?php echo Html::img("logo.jpg","Logo","width='300' style='margin-top:20px;margin-bottom:20px'") ?>
         <?php View::content(); ?>

    </div>
    <div class="row">
        <div class="col-md-4 col-sm-3 col-xs-0 "></div>
        <div class="col-md-4 col-sm-6 col-xs-12 ">
                <?php echo Form::open(); ?>
                    <div class="form-group">
                        <?php echo Form::label("Usuario","login"); ?>
                        <?php echo Form::text("login","class='form-control'"); ?>
                    </div>
                    <div class="form-group">

                        <?php echo Form::label("Password","password"); ?>
                        <?php echo Form::pass("password","class='form-control'"); ?>
                    </div>
                    <?php echo Form::submit("Ingresar","class='btn btn-default'"); ?>
                    <?php echo Html::link('registro/nuevo','Nuevo Registro',"class='btn btn-default'") ?>
                <?php echo Form::close(); ?>
        </div>
        <div class="col-md-4 col-sm-3 col-xs-0 "></div>
    </div>

</div>
